# Generated by Django 2.2.28 on 2024-03-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratearant', '0007_alter_restaurant_openingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratearant.Restaurant'),
        ),
    ]
